redo commits.json because %s omits the rest of the commit body
[alt-schedule-parser-tester]
[ascended-cat]
[assembly]
[blockly]
[blog]
ERROR: couldn't find file corresponding to 404/index.html. candidates: NONE
note: HELLO-WORLD/index.html -> _posts/2016-12-27-HELLO-WORLD.md
note: SECOND-POST/index.html -> _posts/2016-12-27-SECOND-POST.md
note: SHOWBALL-PROBLEM-JOURNAL/index.html -> _posts/2017-1-26-SHOWBALL-PROBLEM-JOURNAL.md
[calculator]
[colour]
[cse15l-lab-reports]
note: any name you choose.html -> any name you choose.md
note: index.html -> index.md
note: lab-report-1-week-2.html -> lab-report-1-week-2.md
note: lab-report-2-week-4.html -> lab-report-2-week-4.md
note: lab-report-3-week-6.html -> lab-report-3-week-6.md
note: lab-report-4-week-8.html -> lab-report-4-week-8.md
note: lab-report-5-week-10.html -> lab-report-5-week-10.md
[cse272-project]
[dating-sim]
[doufu]
[dulcinea]
[dumb-multiplayer-server]
[evo]
[eyo-dictionary]
WARN: may have received multiple commits index.html
The fun stuff is here!

The index files have all the fun stuff, actually; dict.js is the boring, yet the most essential part of the entire thing.
|d6e2ef321790bc91cd8cd1849a5f546d7d422833|2016-09-11 10:18:48 -0700|Create index.html
[flex10-protect]
[fun-gunn-run]
[gamepro5.github.io]
[guestbook]
[gunn-map]
[gunn-student-sim]
[happynumbers]
[HEALTH-AMONG-US]
[hello-world]
note: advent-of-code/2021/index.html -> advent-of-code/2021/README.md
note: deobf/index.html -> deobf/README.md
note: hh23-rhythm/src/javascript-impatience/todo.html -> hh23-rhythm/src/javascript-impatience/todo.md
note: hh23-rhythm/index.html -> hh23-rhythm/README.md
note: random-item-skyblock/index.html -> random-item-skyblock/README.md
note: slicedlime-vanilla-worldgen/index.html -> slicedlime-vanilla-worldgen/README.md
note: test/a/s/s/e/t/s/index.html -> test/a/s/s/e/t/s/README.md
note: test/asus/soc-med-controller/index.html -> test/asus/soc-med-controller/README.md
note: test/cse110-reconnaissance.html -> test/cse110-reconnaissance.md
note: test/demo-btns.html -> test/demo-btns.md
note: test/git-notes.html -> test/git-notes.md
note: test/link test.html -> test/link test.md
note: test/mdmdmdd.html -> test/mdmdmdd.md
note: test/uhh.html -> test/uhh.md
note: ucsd-commencement-voices/index.html -> ucsd-commencement-voices/README.md
note: ucsd-schedule-gen/index.html -> ucsd-schedule-gen/README.md
note: git.html -> git.md
note: index.html -> index.md
note: index.html -> index.md
note: privacy-policy.html -> privacy-policy.md
note: SECURITY.html -> SECURITY.md
[htmlblocks]
[htmlifier]
[intuitive-gunn-website]
WARN: may have received multiple commits index.html
commit some changes I had left uncommitted

|9fcc03c88fae2ab8ee5529428be83d077ac38752|2019-01-06 17:34:56 -0800|hmmm

[longer-tweets]
note: always-var/index.html -> _posts/2020-09-06-always-var.md
note: better-tests/index.html -> _posts/2018-05-13-better-tests.md
note: closing-html/index.html -> _posts/2020-08-24-closing-html.md
note: colored-functions/index.html -> _posts/2025-07-26-colored-functions.md
note: creating-this-blog/index.html -> _posts/2018-05-05-creating-this-blog.md
note: ctf/index.html -> _posts/2022-05-08-ctf.md
note: flatland-chem/index.html -> _posts/2020-03-21-flatland-chem.md
note: flawless-new-english/index.html -> _posts/2018-05-06-flawless-new-english.md
note: gamepro5-translation/index.html -> _posts/2019-01-01-gamepro5-translation.md
note: google-anal/index.html -> _posts/2023-04-29-google-anal.md
note: google-ctf/index.html -> _posts/2022-07-08-google-ctf.md
note: html-xss/index.html -> _posts/2020-11-27-html-xss.md
note: js/index.html -> _posts/2022-08-06-js.md
note: json-is-hard/index.html -> _posts/2020-07-06-json-is-hard.md
note: json-lang/index.html -> _posts/2020-08-11-json-lang.md
note: lactf/index.html -> _posts/2024-02-18-lactf.md
note: leopard/index.html -> _posts/2020-07-06-leopard.md
note: life-after-death/index.html -> _posts/2018-05-06-life-after-death.md
note: lol-vocabulary/index.html -> _posts/2018-06-17-lol-vocabulary.md
note: major/index.html -> _posts/2021-12-18-major.md
note: martian-math/index.html -> _posts/2018-10-18-martian-math.md
note: matrix-lab/index.html -> _posts/2022-10-02-matrix-lab.md
note: microplastics/index.html -> _posts/2025-10-23-microplastics.md
note: phonology/index.html -> _posts/2019-01-02-phonology.md
note: pickles/index.html -> _posts/2022-10-26-pickles.md
note: pronouns/index.html -> _posts/2019-01-02-pronouns.md
note: racism-response/index.html -> _posts/2019-07-18-racism-response.md
note: react/index.html -> _posts/2025-09-16-react.md
note: scratch-www-troubles/index.html -> _posts/2018-07-01-scratch-www-troubles.md
note: sdctf24/index.html -> _posts/2024-05-14-sdctf24.md
note: securly-bypass/index.html -> _posts/2020-10-22-securly-bypass.md
note: slop/index.html -> _posts/2025-10-04-slop.md
note: squash/index.html -> _posts/2025-10-23-squash.md
note: test/index.html -> _posts/2018-05-05-test.md
note: ucsd-colleges/index.html -> _posts/2021-11-25-ucsd-colleges.md
note: ugwa-alt-schedules/index.html -> _posts/2019-08-10-ugwa-alt-schedules.md
note: ugwa-colours/index.html -> _posts/2021-08-31-ugwa-colours.md
note: underground-schoology/index.html -> _posts/2019-02-23-underground-schoology.md
note: vertex-buffer-not-big-enough/index.html -> _posts/2024-04-18-vertex-buffer-not-big-enough.md
note: index.html -> index.md
[mars]
[offline-ucsd-map]
[olamreee]
[ovinetopia]
[platformre]
WARN: may have received multiple commits levelmaker.html
Redirects, fixes

|664997996303af585f83b3f6406c9b095261ed32|2016-09-21 19:59:40 -0700|Added level maker

WARN: may have received multiple commits randomlevelgen.html
Redirects, fixes

|7b92d77c9f79df15891580e73644cfd529e113b1|2016-09-20 19:18:51 -0700|Added test level

[qr]
[reiglutopia]
[roots]
[scratch-blocks]
note: index.html -> index.md
[scratch-gui]
[scratch-vm]
WARN: may have received multiple commits index.html
Build for $(git log --pretty=format:%H -n1)

|93f65039e733ce61aa2e0e5d3fe2957202540983|2016-09-25 18:06:30 +0000|Build for 9f59efb39e9851759a502f49a84d6da5ff5f34f0
170adf41b7e4c11ecb558bd5bb293008d3a539c6
6d37d4a5bbf9276e9ce620bdc64c6a112007f9c2
36fc03851c58c1fc39e11ec4b29fca969fcc0461
2d736f2b871fdcec1c6cd9c063be3d72956db933
a118d500565f72aa86f256a119d95d46b7546c4a
a687184c3c5298188d2f4f4a226502bb5c40a4e4
aa5e8d264888bcdd8ed6d090b5d0b05e94ded8ca
f9efc2b4bcf63a38794156e832320d693d6ff05b
32b4374a56c946ca4aa7180a7aca37af0bf66732
bb7dee60871cf630cc6eb3dced549a939edd9975
e6896647331ffdfb6464fcbf2d4e91d9b8206c43
9884c583a92f154e8f01af8953b6b9c54bded5ce
4e547556a8065353e34009f798e170103404c0d0
fa10a2279acc8450baedcb583b9b01a1ab2744e6
499ba5235ca0316fccb95660ee0cef069a4996e6
c02ee88d0247528f8fc0911c0fa057f60131d205
13f287e8712fdd2cfeed31a0d61893f4279385a3
470f686662ac5e057c05fa5739ed46f85cf4e2da
9744bcbb7060a7266168bb84e76a7b6ed9eb6810
542899949eefb8921a8dcbd24b7127497caa34d3
6b3f0d3d8af7f487856d3b28753921d9bbb2ebe6
89873308531b8be701292fbbe8af65546fc17279
9b4433069e4d20cf210ee3849b1f5508e0576544
1ebee14eb0f6f6b6922b1e76caf526c1daae2423
b6e30a7b23e5ebad5e6f2c89c4158593ef4b4fd7
dec5d054c842b49b1e323eda1589ff313b1a7111
6b08b95b97103d9d188629508328f4ba44c50e50
08b40b4d1daa5adb32ebc7325e9489c0a6545023
833c5ed313be8c07c73114f3b62d7c3d0512cc87
c357a62005eaa60359954fb013bf9fc1f3e07c0c
91cdec15474d86b960f64ce952c0ff432d524fbe
bbea1af5a34b265e3f112b044aa38d7d4564c801
ebbfe881db6033c454bff1ed7a65291d7e83b2da
79346c0925e41d14543c8bd9e96961495f805c37
40b530fa7e134dac857d2519fc62daec783a09f3
d93eeed05d21dbfd5e8a844eabe3861fef45c466
5df0acc895a552067c43606ef1728437218723e0
797f844de30df394068026bed2e7c09b7508d2a9
14feb64005fa33b172d165e1cae59a3f47e8a3a3
f7e339f7c2609341f0b57044c78e04421f10eaae
3fcd70a8028f33050189ea029996e26bef874910
3dbfc3fdb6e3a37be5367bff4f638f6cf949fb88
9a8b68643a0a67e4913e8a58bdcb2b23b7105b5a
7caf8e588aa61f00b55525a31a50da3c9afae852
2b84c8d0fec6e8d31f11bb5177dfc28aad2a290b
8e217a75ab1045808a547e21dcd39d1fe809e39b
e831866789487021398f73558e1e09054dde485e
86f136dd1030e27233b4bdc1ff000771a98ee3fb
77d0376b1576d9126bb42762d0e5e10fa3cb36ae
fc4c5023e14ae6e4d6eb1c04f19189a65b8a2ca1
ae89cfbb6b8f76b57eb5aea041c10562b52423f0
eb69d042081f4472f4a65c8dd0aea2e645d7cb26
1437a358e155e6dd4c0a7b2e668e3c359982c6b4
bb48189e6f111ec56e040b807d571d2a3874f59f
4586507a8a85e7ea785273458f6264fa7524a1a1
602cb47a1e1495fb833a1f56e6facfa823db933f
f981e8747f9a2820a86407e06ba40e035966306e
220d614a9d6dfce72efc788ab548be59f58c009d
020250e25803e20dfb5674c38c974c7ec98652f2
c70e9759a97079ececad132e43064d89e458ccac
75212c595882425e0d3e9ef92eb9d04addc79ef7
3e749fb9f107027459d6c5366cb180901d310056
bdc95cffc08c91c31763c68c89a668782f2f2531
1098a0698588b7c0d65ad5477779301fb8da3be3
29a595345a2fb09f30497f6f5143548af68d9b36
3ccfdf3df0fd82a675fc7ed8e45647198a07ce8f
40c90bbcc76291c589fc50f375b51bb80746a322
64b82f4dc23dd44be177629c02b3ca42dcc6e2ed

WARN: may have received multiple commits suite.html
Build for $(git log --pretty=format:%H -n1)

|b85badcedd835b7957e3357407de20393be2467b|2018-01-23 17:02:20 +0000|Build for 115184a2a39b990dee9218aa15081b334516e1a8

WARN: may have received multiple commits video-sensing.html
Build for $(git log --pretty=format:%H -n1)

|42f75a805141190fbaf7cac4da74e2888048203c|2018-04-05 00:04:51 +0000|Build for 21ae14c4993155e9a61af44fd9d70880076106dd

[sheep-sim]
[skejl]
[sheeptester.github.io]
[text-save]
[theflat]
[themes]
[thingkingland]
[thirty-eight]
[toastia]
[toki-pona]
[ucsd-classrooms]
[ucsd-sunset]
[unclear-target-w-very-confusing-critique]
[uxdy]
[word-prediction]
[words-go-here]
WARN: may have received multiple commits htmlifier/index.html
Redirect to new HTMLifier repository

|c9f2f32d3da0abc33a3db683f198bb899ecb0f05|2019-02-09 16:04:29 -0800|Scratch 3.0 HTMLifier

[yesnt]
WARN: may have received multiple commits index.html
It has been m i n i f i e d

|904567c650e9af747a4a8790338173fb7b9917cb|2019-04-13 20:49:18 -0700|lighting test